title = "Cowrie"
baseURL = "https://www.cowrie.org/"
languageCode = "en-us"
theme = "ananke"
# theme = "hugo-theme-lean-launch-page"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 8
googleAnalytics = "UA-125411124-1"
enableRobotsTXT = false

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Cowrie SSH and Telnet Honeypot"
#  facebook = ""
  twitter = "https://twitter.com/micheloosterhof"
#  instagram = ""
#  youtube = ""
  github = "https://github.com/cowrie/cowrie"
#  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/honeybee.jpg"
  recent_posts_number = 3

# lean
  tagline = "Cowrie is creating innovative deception solutions for todays market"
  mailchimpURL = "https://oosterhof.us3.list-manage.com/subscribe/post?u=672cbf1ebdea7ab81d1fcf8cc&amp;id=f87589bcd8"
