title = "Cowrie SSH and Telnet Honeypot"
baseURL = "https://www.cowrie.org/"
languageCode = "en-us"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 8
googleAnalytics = "UA-125411124-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/micheloosterhof"
  instagram = ""
  youtube = ""
  github = "https://github.com/cowrie/cowrie"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/honeybee.jpg"
  recent_posts_number = 2
